routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



$optionalRoutes = function () {
    Route::get('/', 'FrontendController@index');
    Route::get('/data.js', 'FrontendController@data');
    Route::get('/work', 'FrontendController@work');
    Route::get('/contact', 'FrontendController@contact');
    Route::get('/gallery', 'FrontendController@gallery');
    Route::get('/photo_blog', 'FrontendController@photoblog');
    Route::get('/industry_news', 'NewsController@index');
    Route::get('/privacy{extension}', 'PolicyController@index')->where('extension', '(?:.html)?');
    Route::post('contact_sent', 'FrontendController@contactSent');
    Route::post('/ja/contact_sent', 'FrontendController@contactSent');
    Route::get('/contact_sent_success', 'FrontendController@contactSentSuccess');
    Route::get('/ja/contact_sent_success', 'FrontendController@contactSentSuccess');
};

Route::get('/news/latest', 'NewsController@latest');
Route::post('/news/posts', 'NewsController@posts');
Route::get('/news/timeLines', 'NewsController@timeLines');
Route::get('/news/mobileTimeLines', 'NewsController@mobileTimeLines');




Route::group(['middleware' => ['preferred.language'], 'prefix' => '{lang?}', 'where' => ['lang' => 'en|ja']], $optionalRoutes);

Route::group(['middleware' => ['preferred.language']], $optionalRoutes);

Auth::routes();

// Check role in route middleware
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth', 'roles'], 'roles' => 'admin'], function () {
    Route::get('', 'AdminController@index');
//    Route::resource('roles', 'RolesController');
//    Route::resource('permissions', 'PermissionsController');
    Route::resource('users', 'UsersController');
    Route::resource('activitylogs', 'ActivityLogsController')->only([
        'index', 'show', 'destroy'
    ]);
    Route::resource('settings', 'SettingsController');
    Route::get('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
    Route::post('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);

    Route::resource('area', 'AreaController');
    Route::resource('news', 'NewsController');
    Route::resource('country', 'CountryController');
    Route::resource('category', 'CategoryController');
    Route::resource('project', 'ProjectController');
    Route::resource('blog', 'BlogController');
    Route::resource('project.image', 'ProjectImagesController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('gallery.primary', 'GalleryPrimaryPhotosController');
//    Route::resource('gallery.secondary', 'GallerySecondaryPhotosController');
});
Route::resource('admin/event-categories', 'Admin\\EventCategoriesController');
Route::resource('admin/project-event-categories', 'Admin\\ProjectEventCategoriesController');

//Route::resource('admin/gallery-primary-photos', 'Admin\\GalleryPrimaryPhotosController');
//Route::resource('admin/gallery-secondary-photos', 'Admin\\GallerySecondaryPhotosController');

app/ProjectImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class ProjectImage extends Model
{
    use LogsActivity;

    const STATUSES = [
        'published',
        'unpublished'
    ];
    

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'project_images';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name_en', 'name_jp', 'image', 'project_id', 'status', 'sort_order'];

    /**
     * Change activity log event description
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getDescriptionForEvent($eventName)
    {
        return __CLASS__ . " model has been {$eventName}";
    }
}

app/Http/Controllers/Admin/ProjectImagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Project;
use App\ProjectImage;
use Illuminate\Http\Request;

class ProjectImagesController extends Controller
{
    /**
     * @param Request $request
     * @param Project $project
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request, Project $project)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $projectimages = ProjectImage::where('name_en', 'LIKE', "%$keyword%")
                ->orWhere('name_jp', 'LIKE', "%$keyword%")
                ->orWhere('image', 'LIKE', "%$keyword%")
                ->orWhere('project_id', 'LIKE', "%$keyword%")
                ->orWhere('status', 'LIKE', "%$keyword%")
                ->orWhere('sort_order', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $projectimages = ProjectImage::where('project_id', $project->id)
                ->orderBy('sort_order', 'ASC')
                ->paginate($perPage);
        }

        return view('admin.project-images.index', compact('projectimages', 'project'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create(Project $project)
    {
        $statuses = array_combine(ProjectImage::STATUSES, ProjectImage::STATUSES);
        return view('admin.project-images.create', compact('project', 'statuses'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request, Project $project)
    {
        $requestData = $request->all();
        $this->validate($request, [
            'name_en' => 'required',
            'name_jp' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg|max:5120',
            'project_id' => 'required',
            'status' => 'required'
        ]);

        $image = $request->file('image');
        $name = uniqid() . '.' . $image->getClientOriginalExtension();
        $destinationPath = public_path('/storage/project-image/');
        $projectImage = $image->move($destinationPath, $name);
        $requestData['image'] = $projectImage->getBasename();

        ProjectImage::create($requestData);

        $url = route('project.image.index', ['project' => $project->id]);
        return redirect($url)->with('flash_message', 'ProjectImage added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show(Project $project, $imageId)
    {
        $projectimage = ProjectImage::findOrFail($imageId);

        return view('admin.project-images.show', compact('projectimage', 'project'));
    }

    /**
     * @param Project $project
     * @param $imageId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Project $project, $imageId)
    {
        $projectimage = ProjectImage::findOrFail($imageId);
        $statuses = array_combine(ProjectImage::STATUSES, ProjectImage::STATUSES);

        return view('admin.project-images.edit', compact('projectimage', 'statuses', 'project'));
    }

    /**
     * @param Request $request
     * @param Project $project
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Project $project, ProjectImage $image)
    {
        $this->validate($request, [
            'name_en' => 'required',
            'name_jp' => 'required',
            'image' => 'image|mimes:jpeg,png,jpg|max:5120',
            'project_id' => 'required',
            'status' => 'required'
        ]);

        $requestData = $request->all();

        $requestImage = $request->file('image');
        if ($request->has('image')) {

            $name = uniqid() . '.' . $requestImage->getClientOriginalExtension();
            $destinationPath = public_path('/storage/project-image/');
            $projectImage = $requestImage->move($destinationPath, $name);
            $requestData['image'] = $projectImage->getBasename();
            @unlink(public_path('/storage/project-image/' . $image->image));
        }

        $image->update($requestData);
        $url = route('project.image.index', ['project' => $project->id]);
        return redirect($url)->with('flash_message', 'ProjectImage updated!');
    }

    /**
     * @param Project $project
     * @param $imageId
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Project $project, ProjectImage $image)
    {
        @unlink(public_path('/storage/project-image/' . $image->image));
        $image->delete();

        $url = route('project.image.index', ['project' => $project->id]);
        return redirect($url)->with('flash_message', 'ProjectImage deleted!');
    }
}

resources/views/admin/project-images/create.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ $project->name_en }} <i class='fa fa-angle-right'></i>
                        Create New Image</div>
                    <div class="card-body">
                        <a href="{{ route('project.image.index', ['project' => $project->id]) }}"
                            title="Back"
                        ><button class="btn
                        btn-warning
                        btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::open([
                            'url' => route('project.image.store', ['project' => $project->id]),
                            'class' => 'form-horizontal',
                            'files'=>true,
                            ])
                        !!}

                        @include ('admin.project-images.form', ['formMode' => 'create'])

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/project-images/edit.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Edit ProjectImage {{ $projectimage->name_en }}</div>
                    <div class="card-body">
                        <a href="{{ route('project.image.index', ['project' => $project->id]) }}"
                           title="Back"><button class="btn btn-warning btn-sm">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::model($projectimage, [
                            'method' => 'PATCH',
                            'url' => route(
                            'project.image.update',
                            [
                                'project' => $project->id,
                                'image' => $projectimage->id
                            ]),
                            'class' => 'form-horizontal',
                            'files' => true
                        ]) !!}

                        @include ('admin.project-images.form', ['formMode' => 'edit'])

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/project-images/form.blade.php
    <div class="form-group{{ $errors->has('name_en') ? 'has-error' : ''}}">
    {!! Form::label('name_en', 'Name En', ['class' => 'control-label']) !!}
    {!! Form::text('name_en', null, ('required' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}
    {!! $errors->first('name_en', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('name_jp') ? 'has-error' : ''}}">
    {!! Form::label('name_jp', 'Name Jp', ['class' => 'control-label']) !!}
    {!! Form::text('name_jp', null, ('required' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}
    {!! $errors->first('name_jp', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('image') ? 'has-error' : ''}}">
    {!! Form::label('image', 'Image', ['class' => 'control-label']) !!}
    <small>585 x 460</small>
    {!! Form::file('image', ($formMode == 'create') ? ['class' => 'form-control', 'required' => 'required'] :
    ['class' => 'form-control']) !!}
    {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('status') ? 'has-error' : ''}}">
    {!! Form::label('status', 'Status', ['class' => 'control-label']) !!}
    {!! Form::select('status', $statuses, null, ('required' == 'required') ? ['class' => 'form-control', 'required' =>
    'required'] :
    ['class' => 'form-control']) !!}
    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('sort_order') ? 'has-error' : ''}}">
    {!! Form::label('sort_order', 'Sort Order', ['class' => 'control-label']) !!}
    {!! Form::number('sort_order', null, ('' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}
    {!! $errors->first('sort_order', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
    {!! Form::hidden('project_id', $project->id) !!}
    {!! Form::submit($formMode === 'edit' ? 'Update' : 'Create', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/admin/project-images/index.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        Project <i class='fa fa-angle-right'></i>
                        {{ $project->name_en }} <i class='fa fa-angle-right'></i>
                        Project Images</div>
                    <div class="card-body">
                        <a href="{{ route('project.index') }}"
                           title="Back"><button class="btn btn-warning btn-sm"><i class="fa
                        fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ route('project.image.create', ['project' => $project->id]) }}"
                           class="btn btn-success btn-sm"
                           title="Add New ProjectImage">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>

{{--                        {!! Form::open([--}}
{{--                            'method' => 'GET',--}}
{{--                            'url' => route('project.image.index', ['project' => $project->id]),--}}
{{--                            'class' => 'form-inline my-2 my-lg-0 float-right',--}}
{{--                            'role' => 'search'--}}
{{--                        ])  !!}--}}
{{--                        <div class="input-group">--}}
{{--                            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">--}}
{{--                            <span class="input-group-append">--}}
{{--                                <button class="btn btn-secondary" type="submit">--}}
{{--                                    <i class="fa fa-search"></i>--}}
{{--                                </button>--}}
{{--                            </span>--}}
{{--                        </div>--}}
{{--                        {!! Form::close() !!}--}}

                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th width='300px'>Name En</th>
                                        <th>Sort Order</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($projectimages as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->name_en }}</td>
                                        <td>{{ $item->sort_order }}</td>
                                        <td>{{ $item->status }}</td>
                                        <td>
                                            <a href="{{ route('project.image.show', [
                                                'project' => $project->id,
                                                'image' => $item->id
                                            ]) }}"
                                               title="View ProjectImage"
                                            ><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i></button></a>
                                            <a href="{{ url('/admin/project/' . $project->id . '/image/' . $item->id .'/edit') }}"
                                               title="Edit ProjectImage">
                                                <button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a>
                                            {!! Form::open([
                                                'method' => 'DELETE',
                                                'url' => route('project.image.destroy', [
                                                    'project' => $project->id,
                                                    'image' => $item->id
                                                ]),
                                                'style' => 'display:inline'
                                            ]) !!}
                                                {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i>', array(
                                                        'type' => 'submit',
                                                        'class' => 'btn btn-danger btn-sm',
                                                        'title' => 'Delete ProjectImage',
                                                        'onclick'=>'return confirm("Confirm delete?")'
                                                )) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $projectimages->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/project-images/show.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">ProjectImage {{ $projectimage->id }}</div>
                    <div class="card-body">

                        <a href="{{ route('project.image.index', ['project' => $project->id]) }}"
                           title="Back"><button class="btn btn-warning btn-sm"><i class="fa
                        fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                            <a href="{{ route('project.image.edit', [
                                'project' => $project->id,
                                'image' =>$projectimage->id]
                                )}}"
                               title="Edit ProjectImage"
                            ><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>
                        {!! Form::open([
                            'method'=>'DELETE',
                            'url' => route('project.image.destroy', [
                                'project' => $project->id,
                                'image' => $projectimage->id
                            ]),
                            'style' => 'display:inline'
                        ]) !!}
                            {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete', array(
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger btn-sm',
                                    'title' => 'Delete ProjectImage',
                                    'onclick'=>'return confirm("Confirm delete?")'
                            ))!!}
                        {!! Form::close() !!}
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $projectimage->id }}</td>
                                    </tr>
                                    <tr>
                                        <th> Name En </th>
                                        <td> {{ $projectimage->name_en }} </td>
                                    </tr>
                                    <tr>
                                        <th> Name Jp </th>
                                        <td> {{ $projectimage->name_jp }} </td>
                                    </tr>
                                    <tr>
                                        <th> Image </th>
                                        <td> <img src='/storage/project-image/{{ $projectimage->image }}' width='500'
                                            /></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection