routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



$optionalRoutes = function () {
    Route::get('/', 'FrontendController@index');
    Route::get('/data.js', 'FrontendController@data');
    Route::get('/work', 'FrontendController@work');
    Route::get('/contact', 'FrontendController@contact');
    Route::get('/gallery', 'FrontendController@gallery');
    Route::get('/photo_blog', 'FrontendController@photoblog');
    Route::get('/industry_news', 'NewsController@index');
    Route::get('/privacy{extension}', 'PolicyController@index')->where('extension', '(?:.html)?');
    Route::post('contact_sent', 'FrontendController@contactSent');
    Route::post('/ja/contact_sent', 'FrontendController@contactSent');
    Route::get('/contact_sent_success', 'FrontendController@contactSentSuccess');
    Route::get('/ja/contact_sent_success', 'FrontendController@contactSentSuccess');
};

Route::get('/news/latest', 'NewsController@latest');
Route::post('/news/posts', 'NewsController@posts');
Route::get('/news/timeLines', 'NewsController@timeLines');
Route::get('/news/mobileTimeLines', 'NewsController@mobileTimeLines');




Route::group(['middleware' => ['preferred.language'], 'prefix' => '{lang?}', 'where' => ['lang' => 'en|ja']], $optionalRoutes);

Route::group(['middleware' => ['preferred.language']], $optionalRoutes);

Auth::routes();

// Check role in route middleware
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth', 'roles'], 'roles' => 'admin'], function () {
    Route::get('', 'AdminController@index');
//    Route::resource('roles', 'RolesController');
//    Route::resource('permissions', 'PermissionsController');
    Route::resource('users', 'UsersController');
    Route::resource('activitylogs', 'ActivityLogsController')->only([
        'index', 'show', 'destroy'
    ]);
    Route::resource('settings', 'SettingsController');
    Route::get('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
    Route::post('generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);

    Route::resource('area', 'AreaController');
    Route::resource('news', 'NewsController');
    Route::resource('country', 'CountryController');
    Route::resource('category', 'CategoryController');
    Route::resource('project', 'ProjectController');
    Route::resource('blog', 'BlogController');
    Route::resource('project.image', 'ProjectImagesController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('gallery.primary', 'GalleryPrimaryPhotosController');
//    Route::resource('gallery.secondary', 'GallerySecondaryPhotosController');
});
Route::resource('admin/event-categories', 'Admin\\EventCategoriesController');
Route::resource('admin/project-event-categories', 'Admin\\ProjectEventCategoriesController');

//Route::resource('admin/gallery-primary-photos', 'Admin\\GalleryPrimaryPhotosController');
//Route::resource('admin/gallery-secondary-photos', 'Admin\\GallerySecondaryPhotosController');

app/GalleryPrimaryPhoto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class GalleryPrimaryPhoto extends Model
{
    use LogsActivity;
    

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'gallery_primary_photos';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'image_thumb', 'image_large', 'sort_order', 'gallery_id', 'inside_text', 'outside_text'];

    

    /**
     * Change activity log event description
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getDescriptionForEvent($eventName)
    {
        return __CLASS__ . " model has been {$eventName}";
    }
}

app/Http/Controllers/Admin/GalleryPrimaryPhotosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Gallery;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\GalleryPrimaryPhoto;
use Illuminate\Http\Request;

class GalleryPrimaryPhotosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request, Gallery $gallery)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $galleryprimaryphotos = GalleryPrimaryPhoto::where('title', 'LIKE', "%$keyword%")
                ->orWhere('image_thumb', 'LIKE', "%$keyword%")
                ->orWhere('image_large', 'LIKE', "%$keyword%")
                ->orWhere('sort_order', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $galleryprimaryphotos = GalleryPrimaryPhoto::where('gallery_id', $gallery->id)
                ->orderBy('sort_order', 'ASC')
                ->paginate($perPage);
        }


        return view('admin.gallery-primary-photos.index', compact('galleryprimaryphotos', 'gallery'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create(Gallery $gallery)
    {
        return view('admin.gallery-primary-photos.create', compact('gallery'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request, Gallery $gallery)
    {
        $this->validate($request, [
            'image_thumb' => 'required|image|mimes:jpeg,png,jpg|max:5120',
            'image_large' => 'required|image|mimes:jpeg,png,jpg|max:5120',
            'gallery_id' => 'required',
        ]);
        $requestData = $request->all();

        $image = $request->file('image_thumb');
        $name = uniqid() . '.' . $image->getClientOriginalExtension();
        $destinationPath = public_path('/storage/gallery-primary-image/');
        $projectImage = $image->move($destinationPath, $name);
        $requestData['image_thumb'] = $projectImage->getBasename();

        $image = $request->file('image_large');
        $name = uniqid() . '.' . $image->getClientOriginalExtension();
        $destinationPath = public_path('/storage/gallery-primary-image/');
        $projectImage = $image->move($destinationPath, $name);
        $requestData['image_large'] = $projectImage->getBasename();

        GalleryPrimaryPhoto::create($requestData);

        $url = route('gallery.primary.index', ['gallery' => $gallery->id]);
        return redirect($url)->with('flash_message', 'Image added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show(Gallery $gallery, $id)
    {
        $galleryprimaryphoto = GalleryPrimaryPhoto::findOrFail($id);

        return view('admin.gallery-primary-photos.show', compact('galleryprimaryphoto', 'gallery'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit(Gallery $gallery, $id)
    {
        $galleryprimaryphoto = GalleryPrimaryPhoto::findOrFail($id);

        return view('admin.gallery-primary-photos.edit', compact('galleryprimaryphoto', 'gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, Gallery $gallery, $imageId)
    {
        $image = GalleryPrimaryPhoto::findOrFail($imageId);
        $this->validate($request, [
            'image_thumb' => 'image|mimes:jpeg,png,jpg|max:5120',
            'image_large' => 'image|mimes:jpeg,png,jpg|max:5120'
        ]);
        $requestData = $request->all();

        $requestImage = $request->file('image_thumb');
        if ($request->has('image_thumb')) {
            $name = uniqid() . '.' . $requestImage->getClientOriginalExtension();
            $destinationPath = public_path('/storage/gallery-primary-image/');
            $galleryImage = $requestImage->move($destinationPath, $name);
            $requestData['image_thumb'] = $galleryImage->getBasename();
            @unlink(public_path('/storage/gallery-primary-image/' . $image->image_thumb));
        }

        $requestImage = $request->file('image_large');
        if ($request->has('image_large')) {
            $name = uniqid() . '.' . $requestImage->getClientOriginalExtension();
            $destinationPath = public_path('/storage/gallery-primary-image/');
            $galleryImage = $requestImage->move($destinationPath, $name);
            $requestData['image_large'] = $galleryImage->getBasename();
            @unlink(public_path('/storage/gallery-primary-image/' . $image->imge_large));
        }

        $image->update($requestData);
        $url = route('gallery.primary.index', ['gallery' => $gallery->id]);
        return redirect($url)->with('flash_message', 'Updated!');
        
//        $galleryprimaryphoto = GalleryPrimaryPhoto::findOrFail($id);
//        $galleryprimaryphoto->update($requestData);
//
//        return redirect('admin/gallery-primary-photos')->with('flash_message', 'GalleryPrimaryPhoto updated!');
    }

    public function destroy(Gallery $gallery, $imageId)
    {
        $image = GalleryPrimaryPhoto::findOrFail($imageId);
        @unlink(public_path('/storage/gallery-primary-image/' . $image->image_thumb));
        @unlink(public_path('/storage/gallery-primary-image/' . $image->image_large));
        $image->delete();

        $url = route('gallery.primary.index', ['gallery' => $gallery->id]);
        return redirect($url)->with('flash_message', 'Deleted!');
    }
}

resources/views/admin/gallery-primary-photos/create.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ $gallery->name_en }} <i class='fa fa-angle-right'></i> Gallery Primary Photos <i class='fa fa-angle-right'></i> Add New Image</div>
                    <div class="card-body">
                        <a href="{{ url('/admin/gallery/' . $gallery->id . '/primary') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::open([
                            'url' => route('gallery.primary.store', ['gallery' => $gallery->id]),
                            'class' => 'form-horizontal',
                            'files'=>true,
                            ])
                        !!}

                        @include ('admin.gallery-primary-photos.form', ['formMode' => 'create'])

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/gallery-primary-photos/edit.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ $gallery->name_en }} <i class='fa fa-angle-right'></i> Gallery Primary Photos <i class='fa fa-angle-right'></i> Edit Image</div>
                    <div class="card-body">
                        <a href="{{ route('gallery.primary.index', ['gallery' => $gallery->id]) }}"
                           title="Back"><button class="btn btn-warning btn-sm"><i class="fa
                        fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::model($galleryprimaryphoto, [
                            'method' => 'PATCH',
                            'url' => route(
                            'gallery.primary.update',
                            [
                                'gallery' => $gallery->id,
                                'image' => $galleryprimaryphoto->id,
                                'primary' => $galleryprimaryphoto->id,
                            ]),
                            'class' => 'form-horizontal',
                            'files' => true
                        ]) !!}

                        @include ('admin.gallery-primary-photos.form', ['formMode' => 'edit'])

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/gallery-primary-photos/form.blade.php
<div class="form-group{{ $errors->has('title') ? 'has-error' : ''}}">
    {!! Form::label('title', 'Project Title', ['class' => 'control-label']) !!}
    {!! Form::text('title', null, ('' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}
    {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('image_large') ? 'has-error' : ''}}">
    {!! Form::label('image_large', 'Image Large', ['class' => 'control-label']) !!}
    <small>... x ...</small>
    {!! Form::file('image_large', ($formMode == 'create') ? ['class' => 'form-control', 'required' => 'required'] :
    ['class' => 'form-control']) !!}
    {!! $errors->first('image_large', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('image_thumb') ? 'has-error' : ''}}">
    {!! Form::label('image_thumb', 'Image Thumbnail', ['class' => 'control-label']) !!}
    <small>... x ...</small>
    {!! Form::file('image_thumb', ($formMode == 'create') ? ['class' => 'form-control', 'required' => 'required'] :
    ['class' => 'form-control']) !!}
    {!! $errors->first('image_thumb', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('outside_text') ? 'has-error' : ''}}">
    {!! Form::label('outside_text', 'Outside Text (city, country)', ['class' => 'control-label']) !!}
    <small>The text that displays on the white screen</small>
    {!! Form::textarea('outside_text', null, ['class' => 'form-control']) !!}
    {!! $errors->first('outside_text', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('inside_text') ? 'has-error' : ''}}">
    {!! Form::label('inside_text', 'Inside Text (Providing)', ['class' => 'control-label']) !!}
    <small>Optional: The text that displays on the black screen on pop up</small>
    {!! Form::textarea('inside_text', null, ('' == 'required') ? ['class' => 'form-control'] : ['class' => 'form-control']) !!}
    {!! $errors->first('inside_text', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group{{ $errors->has('sort_order') ? 'has-error' : ''}}">
    {!! Form::label('sort_order', 'Sort Order', ['class' => 'control-label']) !!}
    {!! Form::number('sort_order', null, ('' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}
    {!! $errors->first('sort_order', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
    {!! Form::hidden('gallery_id', $gallery->id) !!}
    {!! Form::submit($formMode === 'edit' ? 'Update' : 'Create', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/admin/gallery-primary-photos/index.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ $gallery->name_en }} <i class='fa fa-angle-right'></i> Gallery Primary Photos</div>
                    <div class="card-body">
                        <a href="{{ route('gallery.primary.create', ['gallery' => $gallery->id]) }}"
                           class="btn btn-success btn-sm"
                           title="Add New ProjectImage">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>

{{--                        {!! Form::open(['method' => 'GET', 'url' => '/admin/gallery-primary-photos', 'class' => 'form-inline my-2 my-lg-0 float-right', 'role' => 'search'])  !!}--}}
{{--                        <div class="input-group">--}}
{{--                            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">--}}
{{--                            <span class="input-group-append">--}}
{{--                                <button class="btn btn-secondary" type="submit">--}}
{{--                                    <i class="fa fa-search"></i>--}}
{{--                                </button>--}}
{{--                            </span>--}}
{{--                        </div>--}}
{{--                        {!! Form::close() !!}--}}

                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>#</th><th>Title</th><th>Sort Order</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($galleryprimaryphotos as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->title }}</td><td>{{ $item->sort_order }}</td>
                                        <td>
                                            <a href="{{ url('/admin/gallery/' . $gallery->id  . '/primary/' .  $item->id) }}" title="View GalleryPrimaryPhoto"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i></button></a>
                                            <a href="{{ url('/admin/gallery/' . $gallery->id  . '/primary/' . $item->id . '/edit') }}" title="Edit GalleryPrimaryPhoto"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a>
                                            {!! Form::open([
                                                'method' => 'DELETE',
                                                'url' => route('gallery.primary.destroy', [
                                                'gallery' => $gallery->id,
                                                'image' => $item->id,
                                                'primary' => $item->id
                                                ]),
                                                'style' => 'display:inline'
                                            ]) !!}
                                                {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i>', array(
                                                        'type' => 'submit',
                                                        'class' => 'btn btn-danger btn-sm',
                                                        'title' => 'Delete GalleryPrimaryPhoto',
                                                        'onclick'=>'return confirm("Confirm delete?")'
                                                )) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $galleryprimaryphotos->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/gallery-primary-photos/show.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ $gallery->name_en }} <i class='fa fa-angle-right'></i> Gallery Primary Photos <i class='fa fa-angle-right'></i> View Image</div>
                    <div class="card-body">

                        <a href="{{ route('gallery.primary.index', ['gallery' => $gallery->id]) }}"
                           title="Back"><button class="btn btn-warning btn-sm"><i class="fa
                        fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ route('gallery.primary.edit', [
                                'gallery' => $gallery->id,
                                'project' => $gallery->id,
                                'image' => $galleryprimaryphoto->id,
                                'primary' => $galleryprimaryphoto->id
                                ])}}"
                           title="Edit"
                        ><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>
                        {!! Form::open([
                            'method'=>'DELETE',
                            'url' => route('gallery.primary.destroy', [
                                'gallery' => $gallery->id,
                                'image' => $galleryprimaryphoto->id,
                                'primary' => $galleryprimaryphoto->id
                            ]),
                            'style' => 'display:inline'
                        ]) !!}
                        {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete', array(
                                'type' => 'submit',
                                'class' => 'btn btn-danger btn-sm',
                                'title' => 'Delete ProjectImage',
                                'onclick'=>'return confirm("Confirm delete?")'
                        ))!!}
                        {!! Form::close() !!}
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $galleryprimaryphoto->id }}</td>
                                    </tr>
                                    <tr>
                                        <th> Title </th>
                                        <td> {{ $galleryprimaryphoto->title }}</td>
                                    </tr>
                                    <tr>
                                        <th> Image Large </th>
                                        <td><img src='/storage/gallery-primary-image/{{ $galleryprimaryphoto->image_large }}'> </td></tr>
                                    </tr>
                                    <tr>
                                        <th> Image Thumb </th>
                                        <td><img src='/storage/gallery-primary-image/{{ $galleryprimaryphoto->image_thumb }}'> </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection